apiVersion: apps/v1
kind: Deployment
metadata:
  name: "myd"

spec:
  replicas: 1
  selector:
    matchLabels:
      env: prod
  template:
    metadata:
      name: "webpod"
      labels:
        env: prod
    spec:
      containers:
      - name: "cont1"
        image: "httpd"
